// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PingController from "./ping_controller"
application.register("ping", PingController)

import PressKeyController from "./press_key_controller"
application.register("press-key", PressKeyController)
